"""add customer profile fields

Revision ID: 19b3255fb835
Revises: 62701e6f861c
Create Date: 2026-06-15 20:58:48.509917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b3255fb835'
down_revision = '62701e6f861c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('suburb', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('postcode')
        batch_op.drop_column('state')
        batch_op.drop_column('suburb')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('street_address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
