"""add pending signup otp table

Revision ID: c29238393bc8
Revises: 19b3255fb835
Create Date: 2026-06-15 21:25:54.468855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29238393bc8'
down_revision = '19b3255fb835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=False),
    sa.Column('otp_sent_at', sa.DateTime(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_signup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_signup_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_signup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_signup_email'))

    op.drop_table('pending_signup')
    # ### end Alembic commands ###
